# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\insertWordTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(418, 107)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.wordLanguageSelect = QtWidgets.QComboBox(Form)
        self.wordLanguageSelect.setMaximumSize(QtCore.QSize(41, 16777215))
        self.wordLanguageSelect.setObjectName("wordLanguageSelect")
        self.wordLanguageSelect.addItem("")
        self.wordLanguageSelect.addItem("")
        self.wordLanguageSelect.addItem("")
        self.wordLanguageSelect.addItem("")
        self.gridLayout.addWidget(self.wordLanguageSelect, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.translationInput = QtWidgets.QLineEdit(Form)
        self.translationInput.setReadOnly(False)
        self.translationInput.setObjectName("translationInput")
        self.gridLayout.addWidget(self.translationInput, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.playTranslationButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playTranslationButton.sizePolicy().hasHeightForWidth())
        self.playTranslationButton.setSizePolicy(sizePolicy)
        self.playTranslationButton.setMaximumSize(QtCore.QSize(49, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/play-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playTranslationButton.setIcon(icon)
        self.playTranslationButton.setIconSize(QtCore.QSize(10, 10))
        self.playTranslationButton.setObjectName("playTranslationButton")
        self.gridLayout.addWidget(self.playTranslationButton, 1, 3, 1, 1)
        self.wordInput = QtWidgets.QLineEdit(Form)
        self.wordInput.setPlaceholderText("")
        self.wordInput.setObjectName("wordInput")
        self.gridLayout.addWidget(self.wordInput, 0, 1, 1, 1)
        self.translationLanguageSelect = QtWidgets.QComboBox(Form)
        self.translationLanguageSelect.setMaximumSize(QtCore.QSize(41, 16777215))
        self.translationLanguageSelect.setObjectName("translationLanguageSelect")
        self.translationLanguageSelect.addItem("")
        self.translationLanguageSelect.addItem("")
        self.translationLanguageSelect.addItem("")
        self.translationLanguageSelect.addItem("")
        self.gridLayout.addWidget(self.translationLanguageSelect, 1, 2, 1, 1)
        self.playWordButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playWordButton.sizePolicy().hasHeightForWidth())
        self.playWordButton.setSizePolicy(sizePolicy)
        self.playWordButton.setMaximumSize(QtCore.QSize(49, 16777215))
        self.playWordButton.setIcon(icon)
        self.playWordButton.setIconSize(QtCore.QSize(10, 10))
        self.playWordButton.setObjectName("playWordButton")
        self.gridLayout.addWidget(self.playWordButton, 0, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/switch-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 4, 2, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dictionarySelect = QtWidgets.QComboBox(Form)
        self.dictionarySelect.setObjectName("dictionarySelect")
        self.horizontalLayout.addWidget(self.dictionarySelect)
        self.dictionaryAddButton = QtWidgets.QPushButton(Form)
        self.dictionaryAddButton.setMinimumSize(QtCore.QSize(0, 0))
        self.dictionaryAddButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.dictionaryAddButton.setObjectName("dictionaryAddButton")
        self.horizontalLayout.addWidget(self.dictionaryAddButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 4)

        self.retranslateUi(Form)
        self.wordInput.editingFinished.connect(Form.translateWord)
        self.playWordButton.clicked.connect(Form.playWord)
        self.playTranslationButton.clicked.connect(Form.playTranslation)
        self.dictionaryAddButton.clicked.connect(Form.saveWord)
        self.pushButton.clicked.connect(Form.switchWordInput)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.wordInput, self.wordLanguageSelect)
        Form.setTabOrder(self.wordLanguageSelect, self.playWordButton)
        Form.setTabOrder(self.playWordButton, self.translationInput)
        Form.setTabOrder(self.translationInput, self.translationLanguageSelect)
        Form.setTabOrder(self.translationLanguageSelect, self.playTranslationButton)
        Form.setTabOrder(self.playTranslationButton, self.dictionarySelect)
        Form.setTabOrder(self.dictionarySelect, self.dictionaryAddButton)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Dictionary:"))
        self.wordLanguageSelect.setItemText(0, _translate("Form", "en"))
        self.wordLanguageSelect.setItemText(1, _translate("Form", "sk"))
        self.wordLanguageSelect.setItemText(2, _translate("Form", "ja"))
        self.wordLanguageSelect.setItemText(3, _translate("Form", "de"))
        self.label_2.setText(_translate("Form", "Translation:"))
        self.label.setText(_translate("Form", "Word:"))
        self.playTranslationButton.setText(_translate("Form", "Play"))
        self.translationLanguageSelect.setItemText(0, _translate("Form", "de"))
        self.translationLanguageSelect.setItemText(1, _translate("Form", "ja"))
        self.translationLanguageSelect.setItemText(2, _translate("Form", "sk"))
        self.translationLanguageSelect.setItemText(3, _translate("Form", "en"))
        self.playWordButton.setText(_translate("Form", "Play"))
        self.dictionaryAddButton.setText(_translate("Form", "Add"))

import resources_rc
