# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindowTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1273, 247)
        MainWindow.setBaseSize(QtCore.QSize(1024, 768))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.graphicsFrame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsFrame.sizePolicy().hasHeightForWidth())
        self.graphicsFrame.setSizePolicy(sizePolicy)
        self.graphicsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graphicsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graphicsFrame.setObjectName("graphicsFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.graphicsFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.toolsFrame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolsFrame.sizePolicy().hasHeightForWidth())
        self.toolsFrame.setSizePolicy(sizePolicy)
        self.toolsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolsFrame.setObjectName("toolsFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.toolsFrame)
        self.gridLayout_2.setContentsMargins(22, 22, 22, 22)
        self.gridLayout_2.setSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.toolsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.toolsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.translationLanguageSelect = QtWidgets.QComboBox(self.toolsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translationLanguageSelect.sizePolicy().hasHeightForWidth())
        self.translationLanguageSelect.setSizePolicy(sizePolicy)
        self.translationLanguageSelect.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.translationLanguageSelect.setObjectName("translationLanguageSelect")
        self.translationLanguageSelect.addItem("")
        self.translationLanguageSelect.addItem("")
        self.translationLanguageSelect.addItem("")
        self.translationLanguageSelect.addItem("")
        self.translationLanguageSelect.addItem("")
        self.gridLayout_2.addWidget(self.translationLanguageSelect, 1, 3, 1, 1)
        self.wordLanguageSelect = QtWidgets.QComboBox(self.toolsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordLanguageSelect.sizePolicy().hasHeightForWidth())
        self.wordLanguageSelect.setSizePolicy(sizePolicy)
        self.wordLanguageSelect.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.wordLanguageSelect.setObjectName("wordLanguageSelect")
        self.wordLanguageSelect.addItem("")
        self.wordLanguageSelect.addItem("")
        self.wordLanguageSelect.addItem("")
        self.wordLanguageSelect.addItem("")
        self.wordLanguageSelect.addItem("")
        self.gridLayout_2.addWidget(self.wordLanguageSelect, 0, 3, 1, 1)
        self.switchLanguageButton = QtWidgets.QPushButton(self.toolsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchLanguageButton.sizePolicy().hasHeightForWidth())
        self.switchLanguageButton.setSizePolicy(sizePolicy)
        self.switchLanguageButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/switch-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.switchLanguageButton.setIcon(icon)
        self.switchLanguageButton.setIconSize(QtCore.QSize(40, 40))
        self.switchLanguageButton.setObjectName("switchLanguageButton")
        self.gridLayout_2.addWidget(self.switchLanguageButton, 0, 4, 2, 1)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1273, 47))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.translationLanguageSelect.setCurrentIndex(4)
        self.wordLanguageSelect.currentTextChanged['QString'].connect(MainWindow.setFromLanguage)
        self.translationLanguageSelect.currentTextChanged['QString'].connect(MainWindow.setToLanguage)
        self.switchLanguageButton.clicked.connect(MainWindow.switchLanguage)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Word Game"))
        self.label.setText(_translate("MainWindow", "Translate to:"))
        self.label_2.setText(_translate("MainWindow", "Tanslate from:"))
        self.translationLanguageSelect.setItemText(0, _translate("MainWindow", "en"))
        self.translationLanguageSelect.setItemText(1, _translate("MainWindow", "it"))
        self.translationLanguageSelect.setItemText(2, _translate("MainWindow", "sk"))
        self.translationLanguageSelect.setItemText(3, _translate("MainWindow", "ja"))
        self.translationLanguageSelect.setItemText(4, _translate("MainWindow", "de"))
        self.wordLanguageSelect.setItemText(0, _translate("MainWindow", "en"))
        self.wordLanguageSelect.setItemText(1, _translate("MainWindow", "it"))
        self.wordLanguageSelect.setItemText(2, _translate("MainWindow", "sk"))
        self.wordLanguageSelect.setItemText(3, _translate("MainWindow", "ja"))
        self.wordLanguageSelect.setItemText(4, _translate("MainWindow", "de"))

import resources_rc
